server:
  port: 8080
spring:
  application:
    name: "UserManagementAPI"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:userdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    resources:
      configUrl: /v3/api-docs/swagger-config

info:
  app:
    name: "users-management"
    description: "Users-Management-System"
    version: "1.0.0"